name: Tests
on:
  workflow_dispatch:
  workflow_call:

jobs:
  unit-test:
    name: Unit tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Install dependencies
        run: python -m pip install tox

      - name: Run tests
        run: tox -e unit

  integration-test-microk8s:
    name: Integration tests (microk8s)
    runs-on: ubuntu-22.04
    timeout-minutes: 90
    needs:
      - unit-test
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          channel: 1.28-strict/stable
          juju-channel: 3.4
          lxd-channel: 5.20/stable

      - name: Run integration tests
        # set a predictable model name so it can be consumed by charm-logdump-action
        run: tox -e integration

      - name: Get contexts
        run: kubectl config view
        if: failure()

      - name: Get juju status
        run: juju status --relations
        if: failure()

      - name: Dump debug log
        if: failure()
        run: |
          for m in $(juju models --format json | jq -r '.models[].name' | grep -v "admin/controller"); do juju debug-log -m $m --replay --ms --no-tail; done
          exit 0

      - name: Dump pods and their logs
        if: failure()
        run: |
          juju status --relations --storage
          kubectl get pods \
              -A \
              -o=jsonpath='{range.items[*]}{.metadata.namespace} {.metadata.name}{"\n"}' \
              --sort-by=.metadata.namespace \
              | grep -v "^\s*$" \
              | while read namespace pod; do \
                   kubectl -n $namespace describe pod $pod; \
                   kubectl -n $namespace logs $pod \
                      --all-containers=true \
                      --tail=100; \
               done
          exit 0
