name: Tests
on:
  workflow_dispatch:
  workflow_call:

jobs:
  unit-test:
    name: Unit tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Install dependencies
        run: python -m pip install tox

      - name: Run tests
        run: tox -e unit

  integration-test-microk8s:
    name: Integration tests (microk8s)
    runs-on: ubuntu-22.04
    needs:
      - unit-test
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          channel: 1.28-strict/stable
          juju-channel: 3.2
          bootstrap-options: '--agent-version=3.2.0'

      - name: Run integration tests
        # set a predictable model name so it can be consumed by charm-logdump-action
        run: tox -e integration -- --model testing

      - name: Get contexts
        run: kubectl config view
        if: failure()

      - name: Get juju status
        run: juju status --relations
        if: failure()

      - name: Get juju logs
        run: juju debug-log --replay --include unit-openfga-k8s-0
        if: failure()

      - name: Get openfga container logs
        run: kubectl logs openfga-k8s-0 -c openfga-k8s -n testing
        if: failure()

      # Hack to overcome lack of tools (cat, tar) in the workload container
      - name: Get openfga config file
        run: |
          juju ssh --container openfga openfga/0 pebble plan
        if: failure()
